<?php
if (!isset($_SESSION)) session_start();
if (!isset($_SESSION['user'])) {
    header("Location: index.php?page=login");
    exit;
}
?>

<div class="create">
    <h2>Crée un projet</h2>

    <form method="POST">
        <p>Titre:</p>
        <input type="text" name="titre" value="<?= isset($projet['titre']) ? htmlspecialchars($projet['titre']) : '' ?>" required/>

        <p>Description:</p>
        <textarea name="description" required><?= isset($projet['description']) ? htmlspecialchars($projet['description']) : '' ?></textarea>

        <p>Image (URL):</p>
        <input type="text" name="image" value="<?= isset($projet['image']) ? htmlspecialchars($projet['image']) : '' ?>" required/>

        <p>Description courte:</p>
        <textarea name="short_description" required><?= isset($projet['short_description']) ? htmlspecialchars($projet['short_description']) : '' ?></textarea>

        <button type="submit">Créer</button>
    </form>

    <a href="index.php?page=board">
        <button type="button">Retourner</button>
    </a>
</div>