<!DOCTYPE html>
<html lang="fr">

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Andada+Pro:ital,wght@0,400..840;1,400..840&display=swap"
        rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Jacquard+12&display=swap" rel="stylesheet">
    <link
        href="https://fonts.googleapis.com/css2?family=Andada+Pro:ital,wght@0,400..840;1,400..840&family=Arvo:ital,wght@0,400;0,700;1,400;1,700&family=Domine:wght@400..700&display=swap"
        rel="stylesheet">
    <link rel="icon" type="image/png" href="assets/img/MP.png">

    <title>Portfolio de Max Pham</title>
    <link rel="stylesheet" href="assets/css/app.css" />
</head>

<body>
    <header>
        <a href="index.php?page=about">
            <h1>Portfolio</h1>
        </a>
    </header>

    <main>
        <?php include $template . '.phtml'; ?>
    </main>

    <footer>
        <p>© Copyright</p>
    </footer>
</body>

</html>